# Generated by Django 4.1.5 on 2023-02-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custore', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='custore.size'),
        ),
    ]
