# Generated by Django 4.1.5 on 2023-03-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custore', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custore.customer')),
                ('products', models.ManyToManyField(to='custore.product')),
            ],
        ),
    ]
